# Generated by Django 4.0.3 on 2022-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0003_alter_orderitem_category_name_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
            preserve_default=False,
        ),
    ]
