# Generated by Django 4.0.3 on 2022-03-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0006_remove_customuser_password_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Customer',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='product_name',
        ),
    ]
