# Generated by Django 4.0.3 on 2022-03-22 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0007_rename_customuser_customer_remove_chef_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='category_name',
        ),
        migrations.AddField(
            model_name='chef',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kritunga.category'),
        ),
    ]
