# Generated by Django 4.0.3 on 2022-03-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0008_remove_chef_category_name_chef_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='status',
            new_name='shef_availability',
        ),
    ]
