# Generated by Django 4.0.3 on 2022-03-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0009_rename_status_chef_shef_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='shef_availability',
            new_name='chef_availability',
        ),
    ]
