# Generated by Django 4.0.3 on 2022-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0011_alter_chef_chef_image_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
