# Generated by Django 4.0.3 on 2022-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0013_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
