# Generated by Django 3.1.4 on 2022-04-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0015_auto_20220411_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
