# Generated by Django 4.0.1 on 2022-05-11 15:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0016_auto_20220411_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='todayorders',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='category_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'biryani'), ('item_key2', 'icecreams'), ('item_key3', 'Chinese')], default=None, max_length=29),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chef',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='kritunga_orderitem',
        ),
    ]
