# Generated by Django 4.0.1 on 2022-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0017_orderitem_todayorders_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='kritunga_orderitem',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, to='kritunga.Products')),
            ],
        ),
    ]
