# Generated by Django 4.0.1 on 2022-05-11 15:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0018_remove_chef_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='category_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'biryani'), ('item_key2', 'icecreams'), ('item_key3', 'Chinese')], default=None, max_length=29),
            preserve_default=False,
        ),
    ]
