# Generated by Django 4.0.1 on 2022-05-11 15:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kritunga', '0019_chef_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='category_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('biryani', 'biryani'), ('icecreams', 'icecreams'), ('Chinese', 'Chinese')], max_length=25),
        ),
    ]
